### ISSUE TITLE
Error when loading module

### ISSUE THREAD

**Issue by oHead** [WilsonLe/payload-oauth2#2]
When loading inside payload-cms dockerized version I get this:
```payload-1   | /home/node/app/node_modules/ts-node/dist/index.js:701
payload-1   |             return old(m, filename);
payload-1   |                    ^
payload-1   | Error [ERR_REQUIRE_ESM]: require() of ES Module /home/node/app/node_modules/payload-oauth2/dist/index.js from /home/node/app/src/payload.config.ts not supported.
payload-1   | Instead change the require of index.js in /home/node/app/src/payload.config.ts to a dynamic import() which is available in all CommonJS modules.
payload-1   |     at require.extensions.<computed> [as .js] (/home/node/app/node_modules/ts-node/dist/index.js:701:20)
payload-1   |     at Object.<anonymous> (/home/node/app/src/payload.config.ts:48:24)
payload-1   |     at m._compile (/home/node/app/node_modules/ts-node/dist/index.js:708:29)
payload-1   |     at require.extensions.<computed> [as .ts] (/home/node/app/node_modules/ts-node/dist/index.js:710:16)
payload-1   |     at loadConfig (/home/node/app/node_modules/payload/dist/config/load.js:28:27)
payload-1   |     at BasePayload.init (/home/node/app/node_modules/payload/dist/payload.js:204:33)
payload-1   |     at getPayload (/home/node/app/node_modules/payload/dist/payload.js:263:44)
payload-1   |     at initHTTP (/home/node/app/node_modules/payload/dist/initHTTP.js:39:51)
payload-1   |     at Payload.init (/home/node/app/node_modules/payload/dist/index.js:27:54)
payload-1   |     at /home/node/app/src/server.ts:55:52
payload-1   |     at step (/home/node/app/src/server.ts:33:23)
payload-1   |     at Object.next (/home/node/app/src/server.ts:14:53)
payload-1   |     at /home/node/app/src/server.ts:8:71
payload-1   |     at new Promise (<anonymous>)
payload-1   |     at __awaiter (/home/node/app/src/server.ts:4:12)
payload-1   |     at start (/home/node/app/src/server.ts:50:34)
payload-1   |     at Object.<anonymous> (/home/node/app/src/server.ts:76:1)
payload-1   |     at m._compile (/home/node/app/node_modules/ts-node/dist/index.js:708:29)
payload-1   |     at require.extensions.<computed> [as .ts] (/home/node/app/node_modules/ts-node/dist/index.js:710:16)
payload-1   |     at main (/home/node/app/node_modules/ts-node/dist/bin.js:154:20)
payload-1   |     at Object.<anonymous> (/home/node/app/node_modules/ts-node/dist/bin.js:238:5)
```

Content inside `payload.config.ts` as following:
```
import { OAuth2Plugin } from 'payload-oauth2'
...
export default buildConfig({
...
  plugins: [
    payloadCloud(),
...
    OAuth2Plugin({
      enabled: true,
      serverURL: process.env.NEXT_PUBLIC_URL || "http://localhost:3000",
      authCollection: "users", // assuming you already have a users collection with auth enabled
      clientId: process.env.CLIENT_ID || "",
      clientSecret: process.env.CLIENT_SECRET || "",
      tokenEndpoint: "some token endpoint",
      scopes: [
        "openid",
      ],
      providerAuthorizationUrl: "some auth endpoint",
      getUserInfo: async (accessToken: string) => {
        const response = await fetch(
          "some user info endpoint",
          { headers: { Authorization: `Bearer ${accessToken}` } }
        );
        const user = await response.json();
        return { email: user.email, sub: user.sub };
      },
      successRedirect: () => "/admin",
      failureRedirect: () => "/login",
      //OAuthLoginButton, // a simple link to authorization path (/api/users/oauth/authorize)
    }),
  ],
...
})
```

> Please note that I'm not a javascript / typescript / somethingscript magician so maybe I'm doing something totally wrong here :smile: please help if you can

**Comment by BlainMaguire** [comment]
Hey I think your issue might be that you're on v2 of payload which uses CommonJS when creating projects for you. The error is because the module you're trying to import is an ESM module. It's worth creating a new project using v3 and install the plugin and see if you get the error.

**Comment by oHead** [comment]
Sure I'll try it, thank you

**Comment by WilsonLe** [comment]
@oHead Still running into the issue?

**Comment by oHead** [comment]
Hi, no it seems that a version switch did the job as you proposed. Works now, thank you very much.
