### ISSUE TITLE
Failed to fetch RSC payload for /api/users/oauth/authorize

### ISSUE THREAD

**Issue by MarkKropf** [WilsonLe/payload-oauth2#3]
@WilsonLe 

While the fallback to browser navigation works, this error does appears briefly with every login.

```
app-index.js:43 Failed to fetch RSC payload for http://localhost:3000/api/users/oauth/authorize. Falling back to browser navigation. 
TypeError: Failed to fetch
    at fetchServerResponse (fetch-server-response.js:72:27)
    at eval (prefetch-cache-utils.js:135:106)
    at Object.task (promise-queue.js:30:38)
    at PromiseQueue.processNext (promise-queue.js:81:186)
    at PromiseQueue.enqueue (promise-queue.js:45:76)
    at createLazyPrefetchEntry (prefetch-cache-utils.js:135:49)
    at getOrCreatePrefetchCacheEntry (prefetch-cache-utils.js:87:12)
    at navigateReducer_noPPR (navigate-reducer.js:102:82)
    at clientReducer (router-reducer.js:25:61)
    at Object.action (action-queue.js:132:55)
    at runAction (action-queue.js:41:38)
    at dispatchAction (action-queue.js:98:9)
    at Object.dispatch (action-queue.js:130:40)
    at eval (use-reducer-with-devtools.js:112:21)
    at eval (app-router.js:107:16)
    at eval (app-router.js:217:21)
    at startTransition (react.development.js:2364:25)
    at Object.push (app-router.js:215:44)
    at navigate (link.js:94:49)
    at Object.startTransition (react.development.js:2364:25)
    at linkClicked (link.js:100:24)
    at onClick (link.js:364:13)
    at executeDispatch (react-dom-client.development.js:30534:5)
    at processDispatchQueueItemsInOrder (react-dom-client.development.js:30570:7)
    at processDispatchQueue (react-dom-client.development.js:30583:5)
    at dispatchEventsForPlugins (react-dom-client.development.js:30591:3)
    at eval (react-dom-client.development.js:30781:12)
    at batchedUpdates (react-dom-client.development.js:27941:12)
    at batchedUpdates$1 (react-dom-client.development.js:6383:12)
    at dispatchEventForPluginEventSystem (react-dom-client.development.js:30780:3)
    at dispatchEvent (react-dom-client.development.js:37026:5)
    at dispatchDiscreteEvent (react-dom-client.development.js:36997:5)
```

**Comment by WilsonLe** [comment]
Sorry for the late reply, and thanks for the report! I never got past the reproduction step until now, but the root cause is identified.

In Next.js App Router, if the OAuth authorize endpoint is opened via `next/link` or `router.push()`, Next first tries to fetch an RSC payload for `/api/users/oauth/authorize`. This endpoint is a Payload API endpoint that returns a `302` redirect to the OAuth provider, not an RSC payload, so Next logs:

`Failed to fetch RSC payload ... Falling back to browser navigation`

The login still works because Next falls back to normal browser navigation.

I opened #68 with a package-side defensive fix: the authorize endpoint now detects Next RSC probe requests (`RSC: 1`, `Next-Router-State-Tree`, `Next-Router-Prefetch`, or `_rsc`) and returns `204 No Content` with no `Location` header. Normal browser authorize requests still return the provider `302`.
